# remote_theme: pages-themes/cayman@v0.2.0

remote_theme: jeffreytse/jekyll-theme-yat

# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-sitemap
#   - jekyll-paginate 
#   - jekyll-remote-theme
#   - github-pages
